import json
import math
import os
from collections import defaultdict

# Settings for Continents Miller Cylindrical Projection
# Full World Map but focused or scaled for continents view
lon0 = 0.0 # Standard center

# For an 800px width SVG:
# Width in radians is 2 * pi. 
# scale * 2 * pi * 60 = 800 => scale = 800 / (2*pi*60) approx 2.122
scale = 2.122
offset_x = 400
offset_y = 300

def project(lon_deg, lat_deg):
    lon = math.radians(lon_deg - lon0)
    lat = math.radians(lat_deg)
    
    # Clamp latitude
    lat = max(min(lat, math.radians(85)), math.radians(-85))
    
    x = lon
    y = 1.25 * math.log(math.tan(math.pi/4 + 0.4 * lat))
    
    svg_x = x * scale * 60 + offset_x
    svg_y = offset_y - (y * scale * 60)
    
    return f"{svg_x:.3f},{svg_y:.3f}"

def get_segments(geometry):
    segments = []
    if geometry['type'] == 'Polygon':
        for ring in geometry['coordinates']:
            for i in range(len(ring)-1):
                p1 = tuple(ring[i])
                p2 = tuple(ring[i+1])
                if p1 == p2: continue
                # Store normalized edge and original direction
                edge = tuple(sorted((p1, p2)))
                segments.append((edge, (p1, p2)))
    elif geometry['type'] == 'MultiPolygon':
        for poly in geometry['coordinates']:
            for ring in poly:
                for i in range(len(ring)-1):
                    p1 = tuple(ring[i])
                    p2 = tuple(ring[i+1])
                    if p1 == p2: continue
                    edge = tuple(sorted((p1, p2)))
                    segments.append((edge, (p1, p2)))
    return segments

def dissolve_to_path(geometries):
    edge_counts = defaultdict(int)
    edge_to_directed = {}
    
    for geom in geometries:
        for edge, directed in get_segments(geom):
            edge_counts[edge] += 1
            if edge not in edge_to_directed:
                edge_to_directed[edge] = []
            edge_to_directed[edge].append(directed)
    
    # Boundary edges appear only once
    boundary_edges = [edge for edge, count in edge_counts.items() if count == 1]
    
    # Build adjacency list
    adj = defaultdict(list)
    for edge in boundary_edges:
        p1, p2 = edge_to_directed[edge][0]
        adj[p1].append(p2)
    
    # Extract rings
    visited_starts = set()
    paths = []
    
    points = list(adj.keys())
    for start_node in points:
        if start_node in visited_starts: continue
        
        current_ring = [start_node]
        curr = start_node
        
        while curr in adj and adj[curr]:
            next_node = adj[curr].pop(0)
            if next_node == start_node:
                current_ring.append(next_node)
                break
            current_ring.append(next_node)
            curr = next_node
        
        if len(current_ring) > 2:
            path = "M" + "L".join([project(p[0], p[1]) for p in current_ring]) + "Z"
            paths.append(path)
            # Mark all points in this ring as used (simplified)
            for p in current_ring:
                visited_starts.add(p)
                
    return "".join(paths)

# Main script
try:
    with open('tmp/ne_10m_admin_0_countries.geojson', 'r', encoding='utf-8') as f:
        data = json.load(f)
except FileNotFoundError:
    print("GeoJSON not found in tmp/")
    exit(1)

continent_groups = defaultdict(list)

for feature in data['features']:
    props = feature['properties']
    cont = props.get('CONTINENT')
    if not cont: continue
    
    continent_groups[cont].append(feature['geometry'])

VALID_CONTINENTS = {'Africa', 'Asia', 'Europe', 'North America', 'South America', 'Oceania', 'Antarctica'}

continent_paths = {}
for cont, geometries in continent_groups.items():
    if cont not in VALID_CONTINENTS:
        continue
    print(f"Processing {cont}...")
    continent_paths[cont] = dissolve_to_path(geometries)

# Write output file
output_dir = 'web/src/components/games/data'
if not os.path.exists(output_dir):
    output_dir = 'src/components/games/data'
if not os.path.exists(output_dir):
    output_dir = '../web/src/components/games/data'

with open(f'{output_dir}/continent-paths.ts', 'w', encoding='utf-8') as f:
    f.write("// Generated by process_continents.py - Dissolved Miller Projection (Scale 2.12)\n")
    f.write("export const CONTINENT_PATHS: Record<string, string> = " + json.dumps(continent_paths, indent=4, ensure_ascii=False) + ";\n")

print(f"Done. Processed {len(continent_paths)} continents.")

