
import json
import math

# Settings for Asia Miller Cylindrical Projection
# Maintains straight lines like Mercator but with less polar distortion
lon0 = 95.0 # Center longitude for Asia

scale = 5.0  # Increased scale to fit view better
offset_x = 420
offset_y = 500

def project(lon_deg, lat_deg):
    # Miller Cylindrical Projection
    # x = lon
    # y = 1.25 * log(tan(pi/4 + 0.4 * lat))
    
    lon = math.radians(lon_deg - lon0)
    lat = math.radians(lat_deg)
    
    # Clamp latitude to avoid tan(pi/2)
    lat = max(min(lat, math.radians(85)), math.radians(-85))
    
    x = lon
    y = 1.25 * math.log(math.tan(math.pi/4 + 0.4 * lat))
    
    # Scale and map to SVG
    # In SVG Y increases downwards, so we negate y from the projection
    svg_x = x * scale * 100 + offset_x
    svg_y = offset_y - (y * scale * 100)
    
    return f"{svg_x:.3f},{svg_y:.3f}"

def geojson_to_svg_path(geometry):
    paths = []
    if geometry['type'] == 'Polygon':
        for ring in geometry['coordinates']:
            path = "M" + "L".join([project(p[0], p[1]) for p in ring]) + "Z"
            paths.append(path)
    elif geometry['type'] == 'MultiPolygon':
        for poly in geometry['coordinates']:
            for ring in poly:
                path = "M" + "L".join([project(p[0], p[1]) for p in ring]) + "Z"
                paths.append(path)
    return "".join(paths)

# Main script
with open('ne_10m_admin_0_countries.geojson', 'r', encoding='utf-8') as f:
    data = json.load(f)

asia_paths = {}
bg_paths = {}

asia_mapping_keys = [
    'Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan',
    'Brunei', 'Cambodia', 'China', 'Cyprus', 'Georgia', 'Hong Kong', 'India',
    'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan',
    'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Macao', 'Malaysia', 'Maldives',
    'Mongolia', 'Myanmar', 'Nepal', 'North Korea', 'Oman', 'Pakistan',
    'Palestine', 'Philippines', 'Qatar', 'Russia', 'Saudi Arabia', 'Singapore',
    'South Korea', 'Sri Lanka', 'Syria', 'Taiwan', 'Tajikistan', 'Thailand',
    'Timor-Leste', 'Turkey', 'Turkmenistan', 'United Arab Emirates',
    'Uzbekistan', 'Vietnam', 'Yemen'
]

bg_countries = [
    'Egypt', 'Greece', 'Bulgaria', 'Romania', 'Ukraine', 'Belarus', 
    'Estonia', 'Latvia', 'Lithuania', 'Finland', 'Norway', 'Sweden',
    'Papua New Guinea', 'Australia', 'Germany', 'Poland', 'Czechia',
    'Austria', 'Hungary', 'Slovakia', 'Italy', 'Libya', 'Sudan', 'Ethiopia',
    'Somalia', 'Kenya'
]

for feature in data['features']:
    props = feature['properties']
    name = props.get('NAME')
    continent = props.get('CONTINENT')
    
    if name in asia_mapping_keys or continent == 'Asia':
        unified_name = name
        if name == "Dem. People's Rep. of Korea": unified_name = 'North Korea'
        if name == 'Republic of Korea': unified_name = 'South Korea'
        
        asia_paths[unified_name] = geojson_to_svg_path(feature['geometry'])
    elif name in bg_countries:
        bg_paths[name] = geojson_to_svg_path(feature['geometry'])

# Sort for consistency
asia_paths = dict(sorted(asia_paths.items()))
bg_paths = dict(sorted(bg_paths.items()))

# Write output files
output_dir = '../web/src/components/games/data'
with open(f'{output_dir}/asia-paths.ts', 'w', encoding='utf-8') as f:
    f.write("// Generated by process_asia_miller.py - Miller Cylindrical Projection\n")
    f.write("export const ASIA_PATHS: Record<string, string> = " + json.dumps(asia_paths, indent=4, ensure_ascii=False) + ";\n")

with open(f'{output_dir}/asia-bg-paths.ts', 'w', encoding='utf-8') as f:
    f.write("// Generated by process_asia_miller.py - Miller Cylindrical Projection\n")
    f.write("export const ASIA_BG_PATHS: Record<string, string> = " + json.dumps(bg_paths, indent=4, ensure_ascii=False) + ";\n")

print(f"Processed {len(asia_paths)} Asian countries with Miller Projection.")
