
import json
import math
import os

# Settings for South America Miller Cylindrical Projection
lon0 = -60.0 # Center longitude for South America
scale = 2.592  # Reduced scale further by 10% (from 2.88)
offset_x = 420
offset_y = 183.71  # Moved map down by 5% as requested (from 174.96)

def project(lon_deg, lat_deg):
    # Miller Cylindrical Projection
    # x = lon
    # y = 1.25 * log(tan(pi/4 + 0.4 * lat))
    
    lon = math.radians(lon_deg - lon0)
    lat = math.radians(lat_deg)
    
    # Clamp latitude to avoid tan(pi/2)
    lat = max(min(lat, math.radians(85)), math.radians(-85))
    
    x = lon
    y = 1.25 * math.log(math.tan(math.pi/4 + 0.4 * lat))
    
    # Scale and map to SVG
    # In SVG Y increases downwards, so we negate y from the projection
    svg_x = x * scale * 100 + offset_x
    svg_y = offset_y - (y * scale * 100)
    
    return f"{svg_x:.3f},{svg_y:.3f}"

def geojson_to_svg_path(geometry):
    paths = []
    if geometry['type'] == 'Polygon':
        for ring in geometry['coordinates']:
            path = "M" + "L".join([project(p[0], p[1]) for p in ring]) + "Z"
            paths.append(path)
    elif geometry['type'] == 'MultiPolygon':
        for poly in geometry['coordinates']:
            for ring in poly:
                path = "M" + "L".join([project(p[0], p[1]) for p in ring]) + "Z"
                paths.append(path)
    return "".join(paths)

def extract_french_guiana(feature):
    """ Extract only the part of France that's in South America """
    if feature['properties']['NAME'] != 'France':
        return None
    
    geometry = feature['geometry']
    sa_parts = []
    
    # Bounding Box for French Guiana in SA
    # lon ~ -55 to -51, lat ~ 2 to 6
    if geometry['type'] == 'MultiPolygon':
        for poly in geometry['coordinates']:
            # Check a sample point in the first ring
            p = poly[0][0]
            if -60 < p[0] < -45 and -5 < p[1] < 10:
                sa_parts.append(poly)
    
    if sa_parts:
        return {
            'type': 'MultiPolygon',
            'coordinates': sa_parts
        }
    return None

# Main script
input_file = 'ne_10m_admin_0_countries.geojson'
with open(input_file, 'r', encoding='utf-8') as f:
    data = json.load(f)

sa_paths = {}
bg_paths = {}

# Primary SA countries
sa_countries_list = [
    'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 
    'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela',
    'Falkland Is.', 'Trinidad and Tobago'
]

# Secondary / Background neighboring regions
bg_subregions = ['Central America', 'Caribbean']

for feature in data['features']:
    props = feature['properties']
    name = props.get('NAME')
    subregion = props.get('SUBREGION')
    
    # Direct match for SA subregion or manual list
    if subregion == 'South America' or name in sa_countries_list:
        sa_paths[name] = geojson_to_svg_path(feature['geometry'])
    
    # Extract French Guiana separately
    if name == 'France':
        fg_geom = extract_french_guiana(feature)
        if fg_geom:
            sa_paths['French Guiana'] = geojson_to_svg_path(fg_geom)
            
    # Neighbors: Central America and Caribbean
    if name not in sa_paths and (subregion in bg_subregions):
        bg_paths[name] = geojson_to_svg_path(feature['geometry'])

# Sort for consistency
sa_paths = dict(sorted(sa_paths.items()))
bg_paths = dict(sorted(bg_paths.items()))

# Write output files
output_dir = '../web/src/components/games/data'
os.makedirs(output_dir, exist_ok=True)

with open(f'{output_dir}/south-america-paths.ts', 'w', encoding='utf-8') as f:
    f.write("// Generated by process_south_america.py - Miller Cylindrical Projection\n")
    f.write("export const SOUTH_AMERICA_PATHS: Record<string, string> = " + json.dumps(sa_paths, indent=4, ensure_ascii=False) + ";\n")

with open(f'{output_dir}/south-america-bg-paths.ts', 'w', encoding='utf-8') as f:
    f.write("// Generated by process_south_america.py - Miller Cylindrical Projection\n")
    f.write("export const SOUTH_AMERICA_BG_PATHS: Record<string, string> = " + json.dumps(bg_paths, indent=4, ensure_ascii=False) + ";\n")

print(f"Processed {len(sa_paths)} South American countries (including French Guiana) with Miller Projection.")
print(f"Processed {len(bg_paths)} background neighbors.")
