// Generated by MapFactory
export const EUROPE_CAPITALS_COORDS: Record<string, { x: number, y: number }> = {
    "Albania": {
        "x": 504,
        "y": 473
    },
    "Andorra": {
        "x": 371,
        "y": 462
    },
    "Austria": {
        "x": 478,
        "y": 403
    },
    "Belarus": {
        "x": 559,
        "y": 337
    },
    "Belgium": {
        "x": 391,
        "y": 374
    },
    "Bosnia and Herz.": {
        "x": 493,
        "y": 449
    },
    "Bulgaria": {
        "x": 529,
        "y": 460
    },
    "Croatia": {
        "x": 475,
        "y": 428
    },
    "Cyprus": {
        "x": 601,
        "y": 530
    },
    "Czech Republic": {
        "x": 464,
        "y": 383
    },
    "Denmark": {
        "x": 451,
        "y": 316
    },
    "Estonia": {
        "x": 539,
        "y": 264
    },
    "Finland": {
        "x": 541,
        "y": 254
    },
    "France": {
        "x": 377,
        "y": 396
    },
    "Germany": {
        "x": 457,
        "y": 354
    },
    "Greece": {
        "x": 532,
        "y": 505
    },
    "Hungary": {
        "x": 498,
        "y": 410
    },
    "Iceland": {
        "x": 201,
        "y": 192
    },
    "Ireland": {
        "x": 315,
        "y": 344
    },
    "Italy": {
        "x": 450,
        "y": 467
    },
    "Kosovo": {
        "x": 513,
        "y": 461
    },
    "Latvia": {
        "x": 535,
        "y": 299
    },
    "Liechtenstein": {
        "x": 429,
        "y": 415
    },
    "Lithuania": {
        "x": 543,
        "y": 328
    },
    "Luxembourg": {
        "x": 404,
        "y": 387
    },
    "Malta": {
        "x": 465,
        "y": 523
    },
    "Moldova": {
        "x": 569,
        "y": 416
    },
    "Monaco": {
        "x": 414,
        "y": 450
    },
    "Montenegro": {
        "x": 499,
        "y": 463
    },
    "Netherlands": {
        "x": 396,
        "y": 356
    },
    "North Macedonia": {
        "x": 515,
        "y": 466
    },
    "Norway": {
        "x": 438,
        "y": 257
    },
    "Poland": {
        "x": 512,
        "y": 357
    },
    "Portugal": {
        "x": 294,
        "y": 498
    },
    "Romania": {
        "x": 549,
        "y": 443
    },
    "Russia": {
        "x": 633,
        "y": 314
    },
    "San Marino": {
        "x": 450,
        "y": 448
    },
    "Serbia": {
        "x": 508,
        "y": 439
    },
    "Slovakia": {
        "x": 484,
        "y": 404
    },
    "Slovenia": {
        "x": 465,
        "y": 426
    },
    "Spain": {
        "x": 333,
        "y": 482
    },
    "Sweden": {
        "x": 491,
        "y": 266
    },
    "Switzerland": {
        "x": 414,
        "y": 417
    },
    "Turkey": {
        "x": 598,
        "y": 487
    },
    "Ukraine": {
        "x": 581,
        "y": 378
    },
    "United Kingdom": {
        "x": 359,
        "y": 366
    },
    "Vatican": {
        "x": 451,
        "y": 468
    },
    "Armenia": {
        "x": 683,
        "y": 484
    },
    "Azerbaijan": {
        "x": 721,
        "y": 482
    },
    "Georgia": {
        "x": 685,
        "y": 469
    },
    "Kazakhstan": {
        "x": 878,
        "y": 370
    }
};
