// Generated by MapFactory
export const EUROPE_CAPITALS_COORDS: Record<string, { x: number, y: number }> = {
    "Vatican": {
        "x": 378,
        "y": 483
    },
    "United Kingdom": {
        "x": 299,
        "y": 395
    },
    "Ukraine": {
        "x": 474,
        "y": 405
    },
    "Turkey": {
        "x": 488,
        "y": 491
    },
    "Switzerland": {
        "x": 343,
        "y": 435
    },
    "Sweden": {
        "x": 403,
        "y": 316
    },
    "Spain": {
        "x": 279,
        "y": 487
    },
    "Slovakia": {
        "x": 398,
        "y": 425
    },
    "Slovenia": {
        "x": 383,
        "y": 443
    },
    "Serbia": {
        "x": 417,
        "y": 453
    },
    "San Marino": {
        "x": 371,
        "y": 460
    },
    "Russia": {
        "x": 515,
        "y": 354
    },
    "Romania": {
        "x": 449,
        "y": 456
    },
    "Portugal": {
        "x": 248,
        "y": 499
    },
    "Poland": {
        "x": 420,
        "y": 388
    },
    "Norway": {
        "x": 361,
        "y": 309
    },
    "Netherlands": {
        "x": 328,
        "y": 387
    },
    "Montenegro": {
        "x": 410,
        "y": 472
    },
    "Moldova": {
        "x": 465,
        "y": 435
    },
    "Monaco": {
        "x": 342,
        "y": 461
    },
    "Malta": {
        "x": 383,
        "y": 520
    },
    "North Macedonia": {
        "x": 422,
        "y": 475
    },
    "Luxembourg": {
        "x": 335,
        "y": 412
    },
    "Lithuania": {
        "x": 444,
        "y": 365
    },
    "Liechtenstein": {
        "x": 354,
        "y": 434
    },
    "Latvia": {
        "x": 438,
        "y": 342
    },
    "Kosovo": {
        "x": 421,
        "y": 470
    },
    "Italy": {
        "x": 371,
        "y": 476
    },
    "Ireland": {
        "x": 264,
        "y": 378
    },
    "Iceland": {
        "x": 174,
        "y": 258
    },
    "Hungary": {
        "x": 409,
        "y": 431
    },
    "Greece": {
        "x": 436,
        "y": 505
    },
    "Germany": {
        "x": 377,
        "y": 386
    },
    "Georgia": {
        "x": 556,
        "y": 477
    },
    "France": {
        "x": 313,
        "y": 419
    },
    "Finland": {
        "x": 443,
        "y": 306
    },
    "Estonia": {
        "x": 441,
        "y": 315
    },
    "Denmark": {
        "x": 372,
        "y": 355
    },
    "Czechia": {
        "x": 382,
        "y": 408
    },
    "Cyprus": {
        "x": 491,
        "y": 525
    },
    "Croatia": {
        "x": 391,
        "y": 445
    },
    "Bulgaria": {
        "x": 433,
        "y": 469
    },
    "Bosnia and Herz.": {
        "x": 405,
        "y": 460
    },
    "Belgium": {
        "x": 325,
        "y": 401
    },
    "Belarus": {
        "x": 458,
        "y": 373
    },
    "Azerbaijan": {
        "x": 585,
        "y": 487
    },
    "Austria": {
        "x": 394,
        "y": 424
    },
    "Armenia": {
        "x": 555,
        "y": 489
    },
    "Andorra": {
        "x": 309,
        "y": 471
    },
    "Albania": {
        "x": 413,
        "y": 480
    }
};
