
import fs from 'fs';
import { geoMercator, geoPath } from 'd3-geo';

// Shared projection logic from existing scripts
const communitiesGeoJSON = JSON.parse(fs.readFileSync('public/maps/spain-communities.json', 'utf8'));
const mainlandFeatures = communitiesGeoJSON.features.filter(f => f.properties.name !== 'Canarias');
const projectionMain = geoMercator()
    .fitExtent([[50, 20], [680, 600]], { type: "FeatureCollection", features: mainlandFeatures });

const pathMain = geoPath().projection(projectionMain);

const MOUNTAINS_DATA = {
    'Pirineos': [
        [-1.8, 43.1], [-1.0, 43.0], [0.0, 42.7], [1.0, 42.5], [2.0, 42.3], [3.1, 42.4]
    ],
    'Cordillera Cantábrica': [
        [-7.5, 43.2], [-6.5, 43.1], [-5.0, 43.0], [-3.5, 43.0], [-2.0, 43.1]
    ],
    'Sistema Ibérico': [
        [-3.2, 42.5], [-2.5, 41.8], [-1.5, 41.0], [-0.5, 40.3], [0.1, 39.8]
    ],
    'Sistema Central': [
        [-7.8, 40.2], [-6.5, 40.3], [-5.5, 40.3], [-4.5, 40.6], [-3.5, 41.0], [-3.0, 41.2]
    ],
    'Sistemas Béticos': [
        [-5.8, 36.5], [-4.5, 36.8], [-3.3, 37.0], [-2.0, 37.4], [-1.0, 38.2]
    ],
    'Sierra Morena': [
        [-7.5, 37.8], [-6.0, 38.0], [-4.5, 38.3], [-3.0, 38.5], [-2.3, 38.4]
    ],
    'Montes de Toledo': [
        [-5.5, 39.3], [-4.5, 39.4], [-3.5, 39.5], [-3.0, 39.4]
    ],
    'Macizo Galaico': [
        [-9.0, 43.0], [-8.5, 43.2], [-8.0, 42.8], [-7.5, 42.5]
    ],
    'Montes de León': [
        [-6.8, 42.7], [-6.4, 42.4], [-6.0, 42.2]
    ],
    'Cordillera Costero-Catalana': [
        [0.8, 40.8], [1.2, 41.2], [1.8, 41.6], [2.5, 42.0]
    ]
};

let output = "// Generated by MapFactory\nexport const SPANISH_MOUNTAINS_PATHS: Record<string, string> = {\n";

Object.entries(MOUNTAINS_DATA).forEach(([name, coords]) => {
    const geojsonFeature = {
        type: "Feature",
        geometry: {
            type: "LineString",
            coordinates: coords
        },
        properties: { name }
    };

    const d = pathMain(geojsonFeature);
    if (d) {
        output += `    "${name}": "${d}",\n`;
    }
});

output += "};\n";

fs.writeFileSync('src/components/games/data/spanish-mountains-paths.ts', output);
console.log("Spanish mountains paths generated!");
