
import fs from 'fs';
import { geoMercator, geoPath } from 'd3-geo';

// Shared projection logic from existing scripts
const communitiesGeoJSON = JSON.parse(fs.readFileSync('public/maps/spain-communities.json', 'utf8'));
const mainlandFeatures = communitiesGeoJSON.features.filter(f => f.properties.name !== 'Canarias');
const projectionMain = geoMercator()
    .fitExtent([[50, 20], [680, 600]], { type: "FeatureCollection", features: mainlandFeatures });

const pathMain = geoPath().projection(projectionMain);

const MOUNTAINS_DATA = {
    'Pirineos': [
        [-1.8, 43.4], [0.0, 43.0], [1.5, 42.8], [3.3, 42.6], [3.4, 42.2], [1.5, 42.4], [0.0, 42.6], [-1.8, 43.1], [-1.8, 43.4]
    ],
    'Cordillera Cantábrica': [
        [-8.0, 43.6], [-6.0, 43.4], [-4.0, 43.3], [-2.5, 43.1], [-2.5, 42.8], [-4.5, 42.9], [-6.5, 43.0], [-8.0, 43.2], [-8.0, 43.6]
    ],
    'Sistema Ibérico': [
        [-3.2, 42.6], [-2.4, 41.8], [-0.5, 40.5], [0.2, 39.8], [0.5, 39.9], [-0.2, 40.8], [-2.0, 42.0], [-3.2, 42.6]
    ],
    'Sistema Central': [
        [-7.5, 40.5], [-5.0, 40.8], [-3.0, 41.3], [-2.8, 41.0], [-5.0, 40.5], [-7.5, 40.2], [-7.5, 40.5]
    ],
    'Sistemas Béticos': [
        [-6.0, 36.6], [-4.0, 37.0], [-2.0, 37.5], [-0.5, 38.8], [-0.2, 38.5], [-1.8, 37.2], [-3.8, 36.7], [-6.0, 36.4], [-6.0, 36.6]
    ],
    'Sierra Morena': [
        [-7.5, 38.3], [-4.5, 38.5], [-2.5, 38.8], [-2.5, 38.4], [-4.5, 38.1], [-7.5, 37.9], [-7.5, 38.3]
    ],
    'Montes de Toledo': [
        [-5.5, 39.6], [-3.0, 39.6], [-3.0, 39.2], [-5.5, 39.2], [-5.5, 39.6]
    ],
    'Macizo Galaico': [
        [-9.2, 43.2], [-7.5, 42.8], [-7.5, 42.2], [-9.2, 42.5], [-9.2, 43.2]
    ],
    'Montes de León': [
        [-7.0, 42.8], [-5.8, 42.5], [-5.8, 42.1], [-7.0, 42.4], [-7.0, 42.8]
    ],
    'Cordillera Costero-Catalana': [
        [0.5, 41.0], [1.5, 41.8], [2.8, 42.3], [3.0, 42.0], [2.0, 41.5], [1.0, 40.8], [0.5, 41.0]
    ]
};

let output = "// Generated by MapFactory\nexport const SPANISH_MOUNTAINS_PATHS: Record<string, string> = {\n";

Object.entries(MOUNTAINS_DATA).forEach(([name, coords]) => {
    const geojsonFeature = {
        type: "Feature",
        geometry: {
            type: "Polygon",
            coordinates: [coords]
        },
        properties: { name }
    };

    const d = pathMain(geojsonFeature);
    if (d) {
        output += `    "${name}": "${d}",\n`;
    }
});

output += "};\n";

fs.writeFileSync('src/components/games/data/spanish-mountains-paths.ts', output);
console.log("Spanish mountains paths generated!");
